### ISSUE TITLE
postfix-policyd-spf-perl 2.0.1-1 permits an SPF failed email

### ISSUE THREAD

**Issue by supersophie** [pbruna/postfix-policyd-spf-perl#1]
Hi,

I have postfix-policyd-spf-python  2.0.1-1  running on Debian 9 / Postfix 3.1.9-0+deb9u2. 
SPF headers are added to incoming messages, but for failed From: headers are incorrectly permitted.

An example header with:
> Return-Path: <tom@der-koelner.de>
> Received: from [179.217.214.104] (helo=[b3d9d668.virtua.com.br]) by smtprelay04.ispgateway.de with esmtpsa (TLSv1:ECDHE-RSA-AES256-SHA:256)
> Received-SPF: Pass (helo) identity=helo; client-ip=80.67.18.16; helo=smtprelay04.ispgateway.de; envelope-from=tom@der-koelner.de; receiver=<UNKNOWN>
> From: REMOVED@REMOVED.co.uk
> X-Sender-Info: tom@der-koelner.de
> X-Priority: Medium
> To: REMOVED@REMOVED.co.uk

My SPF records: 

> "v=spf1 mx a a:elk.REMOVED.co.uk -all"
> "spf2.0/mfrom a mx a:elk.REMOVED.co.uk ~all"

My IP is niether 80.67.18.16 nor 179.217.214.104.

Config: 

> cat /etc/postfix-policyd-spf-python/policyd-spf.conf 
> debugLevel = 1 
> TestOnly = 1
> HELO_reject = Fail
> Mail_From_reject = Fail
> PermError_reject = False
> TempError_Defer = False
> skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1
> 

Postfix main.cf

> smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_destination, check_policy_service unix:private/policyd-spf, reject_non_fqdn_sender, reject_rbl_client REMOVED.sbl-xbl.dq.spamhaus.net, reject_rbl_client hostkarma.junkemailfilter.com=127.0.0.2, permit
> policyd-spf_time_limit = 3600

Is this a bug or a config issue?  SPF fails are also reported, so it worked on some incoming emails.

Regards, So.

**Comment by supersophie** [comment]
I wonder if this can be solved for spam email forged with my own addresses on my server with this?

> Reject_Not_Pass_Domains = REMOVED.co.uk

**Comment by pbruna** [comment]
@supersophie You have `~all` at the end of the SPF configuration, that means that the message is not going be blocked automatically.
