### ISSUE TITLE
What does line 216 does?

### ISSUE THREAD

**Issue by vldmitrofanov** [pbruna/postfix-policyd-spf-perl#2]
I'm not a perl dev but it seems to me this line  is garbage

https://github.com/pbruna/postfix-policyd-spf-perl/blob/d1b4ed9a47704dec1c1dba477a19ddb1b924deb1/postfix-policyd-spf-perl.pl#L216

**Comment by pbruna** [comment]
Hello @vldmitrofanov 
The line `216` is a continuation of the line `215`.
It could be written also as:

```perl
if ($helo_result->is_code('fail')) {
    my $helo_authority_exp  = $helo_result->authority_explanation;
}
```
